'use strict';

//////////////////////////////
// 79 PROJECT #2: Modal Window
/**
 * Objective: Display modal when click button
 * Let's Start storing elements on variables
 */

/* const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btn = document.querySelector('.close-modal');
const btnsOpenModal = document.querySelectorAll('.show-modal');
//querySelectorAll to select elements with same class
console.log(btnsOpenModal);
//Why the loop ?  Since we have more than 1 button with the class '.show-modal', when that selection was stored in the variable, it created a kind of array and for arrays, we have to use loops
for (let i = 0; i < btnsOpenModal.length; i++) {
  console.log(btnsOpenModal[i].textContent); //here we're printing in to console the text (textContent) of each elements [i] that has the 'show-modal' class, stored in the 'btnsOpenModal'
}
 */

//////////////////////////////
// 80 Working With Classes
/* 
const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
const btnsOpenModal = document.querySelectorAll('.show-modal'); //querySelectorAll to select elements with same class
// console.log(btnsOpenModal);

// To avoid repeting the same piece of code to remove/add class 'hidden' from different elements, we create a function stored in a var and call it inside the addEventListener arguments whed needed
const openModal = function () {
  console.log('Button clicked');
  modal.classList.remove('hidden');
  overlay.classList.remove('hidden');
};
const closeModal = function () {
  modal.classList.add('hidden');
  overlay.classList.add('hidden');
};

for (let i = 0; i < btnsOpenModal.length; i++) {
  // to open modal
  btnsOpenModal[i].addEventListener('click', openModal); // here we don't add the braces () because it would be executed as soon as the page is load; So removing the braces, the function is call just when the event defined before (click) occurs.

  // to close modal by clicking X
  btnCloseModal.addEventListener('click', closeModal);

  // to close modal by clicking outside modal
  overlay.addEventListener('click', closeModal);
}
 */

//////////////////////////////
// 81 Handling an "Esc" Keypress Event

/**Keyboard events are called 'global events' because they do not happen on one specific element*/

const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
const btnsOpenModal = document.querySelectorAll('.show-modal');
// console.log(btnsOpenModal);

const openModal = function () {
  console.log('Button clicked');
  modal.classList.remove('hidden');
  overlay.classList.remove('hidden');
};
const closeModal = function () {
  modal.classList.add('hidden');
  overlay.classList.add('hidden');
};
// Remind: Everything inside the loop will occurs the same time as the number of the elements in the array; In this case, 3 times (3 buttons)
for (let i = 0; i < btnsOpenModal.length; i++) {
  // to open modal
  btnsOpenModal[i].addEventListener('click', openModal);

  // to close modal by clicking X
  btnCloseModal.addEventListener('click', closeModal);

  // to close modal by clicking outside modal
  overlay.addEventListener('click', closeModal);

  // When an event like click or keydown occurs, JS generate an object containing all the information about the event itself and we can access that object in the event handler function - thats how we'll know exactly what key on keyboard was pressed
  document.addEventListener('keydown', function (e) {
    //'e' is for event
    //console.log('A key was pressed');
    //console.log(e); // details of the object generated by JS printed in the console when 'Esc' is pressed (it could be any other key): => KeyboardEvent {isTrusted: true, key: 'Escape', code: 'Escape', location: 0, ctrlKey: false, …}
    console.log(e.key); // '.key' will show us directly the key that was pressed => Escape (Esc) intead the entire event object

    // "IF the key pressed is ESC and IF the modal tag DON'T contain the 'hidden' class, then close modal"
    if (e.key === 'Escape' && !modal.classList.contains('hidden')) {
      closeModal(); //here we need the braces !
    }
  });
}
